stages:
  - dockerize
  - deploy

variables:
  IMAGE_TAG: bracketgg/api-server:latest
  CONTAINER_NAME: api-server

dockerize-develop:
  stage: dockerize

  only:
    - develop

  script:
    - docker build -f ./Dockerfile -t $IMAGE_TAG .
    - docker image prune -f

  tags:
    - develop

deploy-develop:
  stage: deploy

  only:
    - develop

  script:
      # 컨테이너 강제 종료 및 삭제
    - docker stop $CONTAINER_NAME || true && docker rm $CONTAINER_NAME || true
    - docker run -d --network bracketnet --name=$CONTAINER_NAME --restart always $IMAGE_TAG
    - docker image prune -f

  tags:
    - develop
