<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<table bgcolor="#FFFFFF" border="1" cellspacing="0" id="i80p" style="-ms-text-size-adjust:100%; -webkit-text-size-adjust:auto; background-color:#ffffff; border-collapse:collapse; border-spacing:0; border:1px solid #eeeeee; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px; margin:0 auto; max-width:600px; min-width:600px; mso-table-lspace:0pt; mso-table-rspace:0pt; padding:65px 80px; width:600px">
	<tbody>
		<tr id="i9d8" style="border:none; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px">
			<td id="a" style="-ms-text-size-adjust:100%; -webkit-text-size-adjust:auto; border-collapse:collapse; border-style:none; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px; mso-table-lspace:0pt; mso-table-rspace:0pt; padding-left:80px; padding-right:80px; padding-top:65px"><a href="http://dev.bracket.gg/" id="ilc8" style="font-size: 16px; line-height: 25px; letter-spacing: -0.16px; font-weight: 400; font-family: 'Noto Sans KR', sans-serif; color: #000000; border: 0; outline: none; text-decoration: none; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: auto;"><img alt="BRACKET.GG" height="14" id="ij2j" src="https://directsend.co.kr/index.php/mail_report_api/image_down/VTczNTg4MA/27" style="-ms-interpolation-mode:bicubic; border:0; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px; outline:none; text-decoration:none" width="102" /></a></td>
		</tr>
		<tr id="ilxfi" style="border:none; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px">
			<td id="title" style="-ms-text-size-adjust:100%; -webkit-text-size-adjust:auto; border-collapse:collapse; border-style:none; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:36px; font-weight:bold; letter-spacing:-0.16px; line-height:48px; mso-table-lspace:0pt; mso-table-rspace:0pt; padding:45px 80px 23px">이메일 주소 인증</td>
		</tr>
		<tr id="itkod" style="border:none; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px">
			<td id="b" style="-ms-text-size-adjust:100%; -webkit-text-size-adjust:auto; border-collapse:collapse; border-style:none; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px; mso-table-lspace:0pt; mso-table-rspace:0pt; padding-left:80px; padding-right:80px">안녕하세요. BRACKET.GG입니다.<br id="iidij" style="font-size: 16px; line-height: 25px; letter-spacing: -0.16px; font-weight: 400; font-family: 'Noto Sans KR', sans-serif; color: #000000;" />
			{{ $userName }}님, 아래 버튼을 클릭하여 이메일 인증을 완료해 주세요.</td>
		</tr>
		<tr id="iac65" style="border:none; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px">
			<td id="c" style="-ms-text-size-adjust:100%; -webkit-text-size-adjust:auto; border-collapse:collapse; border-style:none; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px; mso-table-lspace:0pt; mso-table-rspace:0pt; padding:30px 80px 65px"><a href="{{ $verifyUrl }}" id="btn" style="line-height: 25px; letter-spacing: -0.16px; font-family: 'Noto Sans KR', sans-serif; border: 0; outline: none; text-decoration: none; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: auto; width: 100%; background-color: #000000; display: block; font-size: 16px; color: #ffffff; font-weight: bold; text-align: center; padding: 15px 0; box-sizing: border-box;" target="_blank">이메일 인증하기 </a></td>
		</tr>
		<tr id="ic36w" style="border:none; color:#000000; font-family:'Noto Sans KR',sans-serif; font-size:16px; font-weight:400; letter-spacing:-0.16px; line-height:25px">
			<td bgcolor="#F2F2F2" id="d" style="-ms-text-size-adjust:100%; -webkit-text-size-adjust:auto; background-color:#f2f2f2; border-collapse:collapse; border-style:none; box-sizing:border-box; color:#8a8a8e; font-family:'Noto Sans KR',sans-serif; font-size:12px; font-weight:400; letter-spacing:-0.12px; line-height:19px; margin:0 auto; max-width:600px; mso-table-lspace:0pt; mso-table-rspace:0pt; padding:65px 80px; width:100%" width="100%">본 메일은 발신전용으로 회신처리되지 않습니다.<br id="itmwe" style="font-size: 16px; line-height: 25px; letter-spacing: -0.16px; font-weight: 400; font-family: 'Noto Sans KR', sans-serif; color: #000000;" />
			문의사항은 BRACKET.GG 고객센터를 이용해 주세요.<br id="ih3am" style="font-size: 16px; line-height: 25px; letter-spacing: -0.16px; font-weight: 400; font-family: 'Noto Sans KR', sans-serif; color: #000000;" />
			<br id="icjj4" style="font-size: 16px; line-height: 25px; letter-spacing: -0.16px; font-weight: 400; font-family: 'Noto Sans KR', sans-serif; color: #000000;" />
			&copy; 2020 BRACKET.GG<br id="i948j" style="font-size: 16px; line-height: 25px; letter-spacing: -0.16px; font-weight: 400; font-family: 'Noto Sans KR', sans-serif; color: #000000;" />
			회사명: BRACKET.GG<br id="in6bf" style="font-size: 16px; line-height: 25px; letter-spacing: -0.16px; font-weight: 400; font-family: 'Noto Sans KR', sans-serif; color: #000000;" />
			CEO: 군인<br id="ijl3n" style="font-size: 16px; line-height: 25px; letter-spacing: -0.16px; font-weight: 400; font-family: 'Noto Sans KR', sans-serif; color: #000000;" />
			주소: 서울특별시 어딘가<br id="iubrs" style="font-size: 16px; line-height: 25px; letter-spacing: -0.16px; font-weight: 400; font-family: 'Noto Sans KR', sans-serif; color: #000000;" />
			전화: 080-822-1450</td>
		</tr>
	</tbody>
</table>
